/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

import javax.swing.JOptionPane;

/**
 *
 * @author saurabh
 */
public class TTT extends javax.swing.JFrame {

    /**
     * Creates new form TTT
     */
    Board tttboard;
    boolean celloccupied[][];
    boolean GameOver;
    Point bestMove;
    public TTT() {
        initComponents();
        tttboard=new Board();
        celloccupied=new boolean[3][3];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        zerooneBT = new javax.swing.JButton();
        oneoneBT = new javax.swing.JButton();
        twooneBT = new javax.swing.JButton();
        twozeroBT = new javax.swing.JButton();
        onezeroBT = new javax.swing.JButton();
        zerozeroBT = new javax.swing.JButton();
        twotwoBT = new javax.swing.JButton();
        onetwoBT = new javax.swing.JButton();
        zerotwoBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        zerooneBT.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        zerooneBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zerooneBTActionPerformed(evt);
            }
        });

        oneoneBT.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        oneoneBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneoneBTActionPerformed(evt);
            }
        });

        twooneBT.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        twooneBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twooneBTActionPerformed(evt);
            }
        });

        twozeroBT.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        twozeroBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twozeroBTActionPerformed(evt);
            }
        });

        onezeroBT.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        onezeroBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onezeroBTActionPerformed(evt);
            }
        });

        zerozeroBT.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        zerozeroBT.setForeground(java.awt.Color.red);
        zerozeroBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zerozeroBTActionPerformed(evt);
            }
        });

        twotwoBT.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        twotwoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twotwoBTActionPerformed(evt);
            }
        });

        onetwoBT.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        onetwoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onetwoBTActionPerformed(evt);
            }
        });

        zerotwoBT.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        zerotwoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zerotwoBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zerozeroBT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onezeroBT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twozeroBT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oneoneBT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zerooneBT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twooneBT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(onetwoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zerotwoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twotwoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zerooneBT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zerozeroBT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zerotwoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneoneBT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onezeroBT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onetwoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twooneBT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twozeroBT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twotwoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zerozeroBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zerozeroBTActionPerformed
        makeMove(0,0);
    }//GEN-LAST:event_zerozeroBTActionPerformed

    private void zerooneBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zerooneBTActionPerformed
        makeMove(0,1);
    }//GEN-LAST:event_zerooneBTActionPerformed

    private void zerotwoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zerotwoBTActionPerformed
        makeMove(0,2);
    }//GEN-LAST:event_zerotwoBTActionPerformed

    private void onezeroBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onezeroBTActionPerformed
        makeMove(1,0);
    }//GEN-LAST:event_onezeroBTActionPerformed

    private void oneoneBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneoneBTActionPerformed
        makeMove(1,1);
    }//GEN-LAST:event_oneoneBTActionPerformed

    private void onetwoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onetwoBTActionPerformed
        makeMove(1,2);
    }//GEN-LAST:event_onetwoBTActionPerformed

    private void twozeroBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twozeroBTActionPerformed
        makeMove(2,0);
    }//GEN-LAST:event_twozeroBTActionPerformed

    private void twooneBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twooneBTActionPerformed
        makeMove(2,1);
    }//GEN-LAST:event_twooneBTActionPerformed

    private void twotwoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twotwoBTActionPerformed
        makeMove(2,2);
    }//GEN-LAST:event_twotwoBTActionPerformed

    void makeMove(int x,int y){
        if(!GameOver){
            if(!celloccupied[x][y]){
                tttboard.makeMove(new Point(x,y), 1);
                celloccupied[x][y]=true;
                printXVal(x,y);
                if(!tttboard.isGameOver()){
                    tttboard.callMiniMax(0, -1);
                    bestMove=tttboard.returnBestMove();
                    tttboard.makeMove(bestMove, -1);
                    celloccupied[bestMove.x][bestMove.y]=true;   
                    printYVal(bestMove.x,bestMove.y);
                    if(tttboard.isGameOver()){
                        GameOver=true;
                        if(tttboard.hasPWon(1))JOptionPane.showMessageDialog(this,"You Won!");
                        else if(tttboard.hasPWon(-1))JOptionPane.showMessageDialog(this,"You Lost!","Game Over",JOptionPane.ERROR_MESSAGE);
                        else JOptionPane.showMessageDialog(this,"It's a Draw");
                    }
                }
                else{
                    GameOver=true;
                    if(tttboard.hasPWon(1))JOptionPane.showMessageDialog(this,"You Won!");
                    else if(tttboard.hasPWon(-1))JOptionPane.showMessageDialog(this,"You Lost!","Game Over",JOptionPane.ERROR_MESSAGE);
                    else JOptionPane.showMessageDialog(this,"It's a Draw");
                }
            }
        }
    }
    
    void printXVal(int x,int y){
        if(x==0&&y==0){
            zerozeroBT.setForeground(java.awt.Color.GREEN);
            zerozeroBT.setText("X");
        }
        else if(x==0&&y==1){
            zerooneBT.setForeground(java.awt.Color.GREEN);
            zerooneBT.setText("X");
        }
        else if(x==0&&y==2){
            zerotwoBT.setForeground(java.awt.Color.GREEN);
            zerotwoBT.setText("X");
        }
        else if(x==1&&y==0){
            onezeroBT.setForeground(java.awt.Color.GREEN);
            onezeroBT.setText("X");
        }
        else if(x==1&&y==1){
            oneoneBT.setForeground(java.awt.Color.GREEN);
            oneoneBT.setText("X");
        }
        else if(x==1&&y==2){
            onetwoBT.setForeground(java.awt.Color.GREEN);
            onetwoBT.setText("X");
        }
        else if(x==2&&y==0){
            twozeroBT.setForeground(java.awt.Color.GREEN);
            twozeroBT.setText("X");
        }
        else if(x==2&&y==1){
            twooneBT.setForeground(java.awt.Color.GREEN);
            twooneBT.setText("X");
        }
        else if(x==2&&y==2){
            twotwoBT.setForeground(java.awt.Color.GREEN);
            twotwoBT.setText("X");
        }
    }
    void printYVal(int x,int y){
        if(x==0&&y==0){
            zerozeroBT.setForeground(java.awt.Color.RED);
            zerozeroBT.setText("0");
        }
        else if(x==0&&y==1){
            zerooneBT.setForeground(java.awt.Color.RED);
            zerooneBT.setText("0");
        }
        else if(x==0&&y==2){
            zerotwoBT.setForeground(java.awt.Color.RED);
            zerotwoBT.setText("0");
        }
        else if(x==1&&y==0){
            onezeroBT.setForeground(java.awt.Color.RED);
            onezeroBT.setText("0");
        }
        else if(x==1&&y==1){
            oneoneBT.setForeground(java.awt.Color.RED);
            oneoneBT.setText("0");
        }
        else if(x==1&&y==2){
            onetwoBT.setForeground(java.awt.Color.RED);
            onetwoBT.setText("0");
        }
        else if(x==2&&y==0){
            twozeroBT.setForeground(java.awt.Color.RED);
            twozeroBT.setText("0");
        }
        else if(x==2&&y==1){
            twooneBT.setForeground(java.awt.Color.RED);
            twooneBT.setText("0");
        }
        else if(x==2&&y==2){
            twotwoBT.setForeground(java.awt.Color.RED);
            twotwoBT.setText("0");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TTT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JButton oneoneBT;
    private javax.swing.JButton onetwoBT;
    private javax.swing.JButton onezeroBT;
    private javax.swing.JButton twooneBT;
    private javax.swing.JButton twotwoBT;
    private javax.swing.JButton twozeroBT;
    private javax.swing.JButton zerooneBT;
    private javax.swing.JButton zerotwoBT;
    private javax.swing.JButton zerozeroBT;
    // End of variables declaration//GEN-END:variables
}
